language: bash

sudo: true
dist: trusty
os: linux

env:
  - OS_CONTAINER=ubuntu
  - OS_CONTAINER=centos

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients:
    - g.legoux@criteo.com
    on_success: always
    on_failure: always

# See https://docs.travis-ci.com/user/docker/
services:
  - docker

install:
  - ./.ci/install.sh
  - make install

script:
  - make test

after_script:
  - cat /tmp/krb5-test-${OS_CONTAINER}.log
  - ls -lR
  - ./.ci/check-version.sh
