language: bash

sudo: true
dist: trusty
os: linux

python: 3.4

notifications:
  email:
    recipients:
    - g.legoux@criteo.com
    on_success: always
    on_failure: always

# See https://docs.travis-ci.com/user/docker/
services:  
  - docker

install:
  - ./.ci/install.sh

script: 
  - make test

after_script:
  - ./.ci/check-version.sh
  - yes | sed s/y/Y/ | make clean
