language: bash

sudo: true
dist: trusty
os: linux

notifications:
  email:
    recipients:
    - g.legoux@criteo.com
    on_success: always
    on_failure: always

# See https://docs.travis-ci.com/user/docker/
services:  
  - docker

install:
  - ./.ci/install.sh

script: 
  - make test

after_script:
  - ./.ci/check-version.sh
