name: Kerberos Docker

on:
  push:
    branches:
      - "master"

env:
  OS_CONTAINER: ubuntu
        
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:      
      - name: Check out repository code
        uses: actions/checkout@v1
      
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Install project
        run: ./.ci/install.sh && make install OS_CONTAINER=${OS_CONTAINER}

      - name: Check version
        run: .ci/check-version.sh
        
      - name: Test
        run: make test TEST_ON_HOST_MACHINE=yes
        
      - name: Finish
        run: |
          cat /tmp/krb5-test-${OS_CONTAINER}.log && \
          ls -lR && \
          ./script/inspect.sh && \
          ./.ci/check-version.sh
      
      
      

