name: Kerberos Docker

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      env:
        CI: OS_CONTAINER=ubuntu
      
      - name: Check out repository code
        uses: actions/checkout@v1
      
      - name: Install
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
        run: ./.ci/install.sh
        run: - make install OS_CONTAINER=${OS_CONTAINER}
        
      - name: Test
        run: make test TEST_ON_HOST_MACHINE=yes
        
      - name: Finish
        run: cat /tmp/krb5-test-${OS_CONTAINER}.log
        run: ls -lR
        run: ./script/inspect.sh
        run: ./.ci/check-version.sh
      
      
      

